#!/usr/bin/perl
# $Id: cgn_emacs_compilestartlisp,v 1.2 2005-06-21 09:19:09 moa Exp $

use strict;

my $tmp = "/tmp/emacsstart.el";
my @dirs = ("/etc/emacs/site-start.d", "/etc/emacs21/site-start.d");
my @el;
my @elc = ($tmp);

foreach my $dir (@dirs) {
    if (-e $dir) {
	opendir(REP, $dir);
	while (defined(my $file = readdir(REP))) {
	    push(@el, $dir."/".$file) if $file =~ m/(.*)\.el$/;
	    push(@elc, $dir."/".$file) if $file =~ m/(.*)\.elc$/;
	}
	closedir(REP);
    }
}

unlink(@elc);

foreach my $file (@el) {
    open(TMP, ">> $tmp");
    print TMP "(byte-compile-file \"$file\")\n";
    close(TMP);
}

chmod(0755, $tmp);
`emacs -q -batch -l $tmp -f batch-byte-compile 2> /dev/null`;
unlink($tmp);
