#!/usr/bin/perl

use Sys::Hostname;
#use POSIX qw(strftime);
#use Net::FTP;

do "/etc/hosts.nib.pl" or exit;
exit unless $server;
exit if hostname() ne $server;

#our $passwd; 
my $log = "/var/log/cgn_majfel.log";
#my $conffile = "/etc/majfel";
#my $user = "webmaster\@coleumes.org";
#my $server = "privftp.pro.proxad.net";
#my ($sec,$min,$hour,$mday,$month,$year,$sday,$aday,$est_dst) = localtime;

my @cvs_files = ("/cvs/cgn-home/moa/racine/.bashrc,v",
		  "/cvs/cgn-home/moa/racine/.emacs.el,v",
		  "/cvs/cgn-home/moa/racine/.gnus.el,v",
		  "/cvs/cgn-home/moa/racine/.forward,v",
		  "/cvs/cgn-home/moa/racine/.procmailrc,v");
#my @home_files = ("/tmp/.bashrc",
#		  "/tmp/.emacs.el",
#		  "/home/moa/.gnus.el",
#		  "/home/moa/.forward",
#		  "/tmp/.procmailrc");
#my @var_files = ("/var/www/moa/index.html",
#		 "/var/www/mrc.css");


#open(LOG, ">> $log");
#print LOG strftime("%Y-%m-%d %H:%M:%S", localtime)." Starting updating files\n";

for (@cvs_files) {
    `cd /home/moa && co -f -q $_ `;
    `chown moa -R /home/moa`;
}
#`cd /var/www && cvs update >/dev/null 2&>/dev/null`;

# create some files depending on the system wide conffile
#`cat /etc/procmailrc > /tmp/.procmailrc && cat /home/moa/.procmailrc >> /tmp/.procmailrc`;
#`cat /etc/bash.bashrc > /tmp/.bashrc`;
#`for file in /etc/profile.d/*.sh ; do echo "# \$file" >> /tmp/.bashrc && cat \$file >> /tmp/.bashrc && echo "" >> /tmp/.bashrc ; done`;
#`cat /home/moa/.bashrc >> /tmp/.bashrc`;
#`cat /etc/emacs/site-start.d/99cgn.el > /tmp/.emacs.el && cat /home/moa/.emacs.el >> /tmp/.emacs.el`;


#do $conffile or exit;
#exit unless $passwd;
#print LOG strftime("%Y-%m-%d %H:%M:%S", localtime)." Conffile ok\n";
#
#print LOG strftime("%Y-%m-%d %H:%M:%S", localtime)." Trying to login on $server with $user...\n";

#my $ftp = Net::FTP->new($server);
#$ftp->login($user, $passwd) or die;
#print LOG "\t\tdone\n";
#$ftp->cwd("/stock");
#for (@home_files) {
#    print LOG strftime("%Y-%m-%d %H:%M:%S", localtime)." put $_\n";
#    $ftp->put($_) or exit;
#}
#$ftp->cwd("/maison");
#for (@var_files) {
#    print LOG strftime("%Y-%m-%d %H:%M:%S", localtime)." put $_\n";
#    $ftp->put($_) or exit;
#}

#print LOG strftime("%Y-%m-%d %H:%M:%S", localtime)." Work done.\n";
#close(LOG);
# End
