#!/bin/sh

NAME=shush-toram
RAMDIRS=/var/log

# Include defaults if available
if [ -f /etc/default/$NAME ] ; then
    . /etc/default/$NAME
fi

# check if any shush-toramdisk active
for RAMDIR in $RAMDIRS; do
    RAMLOCK=/var/lock/shush-`echo $RAMDIR | sed s@/@@g`.lock
    # go check the next if no lock found
    [ ! -f $RAMLOCK ] && continue
    # update the harddisk with data on ramdisk
    /etc/init.d/$NAME reload >/dev/null
    # restart it to recreate a bigger tmpfs if need be
    # (no --output=pcent option in old version of df, so let's do this
    # each day)
    /etc/init.d/$NAME restart >/dev/null
    break
done

exit 0
# EOF

