#!/bin/bash
#
# Copyright (c) 2013 Mathieu Roy <yeupou--gnu.org>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307
#   USA

# REQUIRES: wget
# http user
USER="www-data"

# steamdb.info base url
STEAMDB="http://steamdb.info/app"
STEAMDB_UNKNOWN="Unknown / Deleted App"

# dont do anything without a nginx config for steam
[ ! -e /etc/nginx/sites-available/steam ] && exit 0

# location of the steam depots
STORE="/srv/www/depot"
[ ! -d $STORE ] && exit 0

# init index 
INDEX=$STORE/depots.html
echo -e "<html><head><title>Index of /`basename $STORE`/</title></head><body><h1>Index of /`basename $STORE`/</h1><hr><pre><a href=\"../\">../</a>" > $INDEX

# go through the list of steam depots
cd $STORE

for depot in *; do
    ## checks
    # depot are directories
    [ ! -d "$depot" ] && continue
    # depot ids are integers
    case "$depot" in *[!0-9]*) continue;; esac

    ## updates
    # get the html webpage
    html=`wget --quiet $STEAMDB/$depot/ -O - `

    # try to extract a header to get a short title
    title=`echo "$html" | awk 'BEGIN{IGNORECASE=1;FS="<h1 class=\"header-title\">|</h1>";RS=EOF} {print $2}'`
    # if it fails, then just take the html title
    [ ! "$title" ] && title=`echo "$html" | awk 'BEGIN{IGNORECASE=1;FS="<title>|</title>";RS=EOF} {print $2}'`

    # if unknown try to get something more specific 
    if [ "$title" == "$STEAMDB_UNKNOWN" ]; then
	title_from_history=`echo "$html" | awk 'BEGIN{IGNORECASE=1;FS="App was deleted, previous name: <b>|</b>";RS=EOF} {print $2}'`
	[ "$title_from_history" ] && title="$title_from_history"
    fi

    # obtain directory size
    size=`du -sh $depot | cut -f 1`
    # if unit is G or T, put in bold
    size_unit=${size//[^a-zA-Z]/}
    case "$size_unit" in G|T) size="<b>$size</b>";; esac

    # put in italic unidentified
    style=""
    [ "$title" == "$STEAMDB_UNKNOWN" ] && style=" style=\"font-style: italic;\""

    # finally add the relevant line
    echo -e "<a href=\"$depot/\">$depot</a>\t\t$size\t<a href=\"$STEAMDB/$depot/\"$style>$title</a>" >> $INDEX
done

# close INDEX
echo -e "</pre><hr></body></html>" >> $INDEX

# EOF
