#!/bin/sh
#
# Mettre à jour certains fichiers qui sont sur le cvs, ce manière arbitraire.
#
# On ne redefinit pas la date, on se fie a celle du filtrage.

. /etc/hosts.nib.sh
if [ ! $SERVER ]; then exit ; fi
if [ `hostname` != $SERVER ]; then exit ; fi 

user=moa
cd /home/$user
co -q -f /home/cvs/cgn-home/$user/racine/.procmailrc,v
co -q -f /home/cvs/cgn-home/$user/racine/.forward,v
chown $user.users -R /home/$user

user=egh
cd /home/$user
co -q -f /home/cvs/cgn-home/$user/.procmailrc,v
co -q -f /home/cvs/cgn-home/$user/.forward,v
chown $user.users -R /home/$user



# End
