#! /bin/sh
### BEGIN INIT INFO
# Provides:          dnsspoof
# Required-Start:    bind9
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start dnsspoof over bind9
# Description:       Start dnsspoof over bind9
### END INIT INFO

set -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/sbin/dnsspoof
NAME=dnsspoof
DESC="DNS spoofer"

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

DNSSPOOF_OPTS=""
if [ -e /etc/default/$NAME ]; then
  . /etc/default/$NAME
fi

start() {
    log_daemon_msg "Starting $DESC" "$NAME"
    start_daemon $DAEMON -f /etc/dnsspoof.conf $DNSSPOOF_OPTS
    log_end_msg $?
}

stop() { 
    log_daemon_msg "Stopping $DESC" "$NAME"
    killall -q -w $DAEMON
    log_end_msg $?
}
stop_nowait() {
    log_daemon_msg "Stopping $DESC" "$NAME"
    killall -q $DAEMON
    log_end_msg $?
}

case "$1" in
    start)
      start
  ;;
    stop)
      stop
  ;;
    restart)
      stop_nowait
      start
  ;;
    *)
      echo "Usage: $NAME {start|stop|restart}"
      exit 1
  ;;
esac
exit 0

# EOF
