#! /bin/sh
### BEGIN INIT INFO
# Provides:          dnsspoof
# Required-Start:    bind9
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start dnsspoof over bind9
# Description:       Start dnsspoof over bind9
### END INIT INFO

set -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/sbin/dnsspoof
NAME=dnsspoof
DESC="DNS spoofer"

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

DNSSPOOF_OPTS=""
if [ -e /etc/default/$NAME ]; then
  . /etc/default/$NAME
fi

case "$1" in
    start)
	log_daemon_msg "Starting $DESC" "$NAME"
	start-stop-daemon --background --start --exec $DAEMON -- -f /etc/dnsspoof.conf $DNSSPOOF_OPTS 
	log_end_msg $?
  ;;
    stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
	start-stop-daemon --stop --exec $DAEMON
	log_end_msg $?
  ;;
    restart)
	$0 stop
        $0 start
  ;;
    *)
      echo "Usage: $NAME {start|stop|restart}"
      exit 1
  ;;
esac
exit 0

# EOF
