#! /bin/sh
### BEGIN INIT INFO
# Provides:          dovecotfix
# Required-Start:    $local_fs $remote_fs $network $syslog $time
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Dovecot fix init script
# Description:       Fix init script for dovecot services
### END INIT INFO

if [ ! -d /var/run/dovecot ]; then 
    mkdir /var/run/dovecot
fi
