#!/bin/sh

### BEGIN INIT INFO
# Provides:          perl-fcgi
# Required-Start:    $local_fs $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Perl for Nginx with spawn-fcgi
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin


# THERE USED TO BE A COMPLICATED AND DETAILLED VERSION OF THIS
# But nginx provides this (2015 march) so lets keep it simple.

NAME="perl-fcgi"
DESC="Perl FastCGI wrapper"

PERL_SCRIPT=/usr/bin/fastcgi-wrapper.pl
FASTCGI_USER=www-data
RETVAL=0

case "$1" in
    start)
      log_daemon_msg "Starting $DESC" "$NAME"
      su - $FASTCGI_USER -c $PERL_SCRIPT
      RETVAL=$?
      log_end_msg $?
  ;;
    stop)
      log_daemon_msg "Stopping $DESC" "$NAME"
      killall -9 fastcgi-wrapper.pl
      RETVAL=$?
      log_end_msg $?
  ;;
    restart)
      log_daemon_msg "Restarting $DESC" "$NAME"
      killall -9 fastcgi-wrapper.pl
      su - $FASTCGI_USER -c $PERL_SCRIPT
      RETVAL=$?
      log_end_msg $?
  ;;
    *)
      echo "Usage: perl-fcgi {start|stop|restart}"
      exit 1
  ;;
esac      
exit $RETVAL

# EOF
