#!/bin/sh

### BEGIN INIT INFO
# Provides:          php-fcgi
# Required-Start:    $local_fs $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start PHP for Nginx with spawn-fcgi
### END INIT INFO

set -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin

. /lib/lsb/init-functions

NAME="php-fcgi"
DESC="PHP FastCGI wrapper"

BIND=127.0.0.1:9000
USER=www-data
PHP_FCGI_CHILDREN=5
PHP_FCGI_MAX_REQUESTS=1000

PHP_CGI=/usr/bin/php-cgi
PHP_CGI_NAME=`basename $PHP_CGI`
PHP_CGI_ARGS="- USER=$USER PATH=/usr/bin PHP_FCGI_CHILDREN=$PHP_FCGI_CHILDREN PHP_FCGI_MAX_REQUESTS=$PHP_FCGI_MAX_REQUESTS $PHP_CGI -b $BIND"
RETVAL=0

start() {
    log_daemon_msg "Starting $DESC" "$NAME"
    start-stop-daemon --quiet --start --background --chuid "$USER" --exec /usr/bin/env -- $PHP_CGI_ARGS
    log_end_msg $?
}
stop() {
    log_daemon_msg "Stopping $DESC" "$NAME"
    killall -q -w -u $USER $PHP_CGI
    log_end_msg $?
}
stop_nowait() {
    log_daemon_msg "Stopping $DESC" "$NAME"
    killall -q -u $USER $PHP_CGI
    log_end_msg $?
}

case "$1" in
    start)
      start
  ;;
    stop)
      stop
  ;;
    restart)
      stop_nowait
      start
  ;;
    *)
      echo "Usage: $NAME {start|stop|restart}"
      exit 1
  ;;
esac
exit 0
