#!/bin/sh

case "$1" in
  start)
   echo "Starting rtorrent..."
   # run screen as root, otherwise rtorrent would own a screen process
   # it cannot access to, due to /dev/pts/* acls.
   screen -dmS rtorrent su --login rtorrent -c rtorrent
   ;;
  stop)
   echo "Stopping rtorrent..."
   killall -s 2 rtorrent
   screen -X "exit" rtorrent
   ;;
  *)
   echo "Usage: $0 {start|stop}"
   exit 1
   ;;
esac

exit 0
