#! /bin/sh
### BEGIN INIT INFO
# Provides:          transmission-daemonfix
# Required-Start:    $local_fs $remote_fs $network $syslog $time
# Required-Stop:     $local_fs $remote_fs $network $syslog
# X-Start-Before:    transmission-daemon
# X-Stop-After:      transmission-daemon
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Create .down file so torrent watch knows the daemon woke up
# Description:       Create .down file so torrent watch knows the daemon woke up
### END INIT INFO

su transmission-daemon -c "touch /home/torrent/watch/.down"

# EOF
