#!/bin/sh

if [ `hostname` = "moe" ]; then
#    /etc/init.d/transmission-daemon stop
    cd /var/lib/transmission-daemon/info/blocklists
    su debian-transmission -c "wget -O btlevel1.gz http://list.iblocklist.com/?list=bt_level1"
    su debian-transmission -c "wget -O nexus23.gz http://list.iblocklist.com/?list=nxs23_ipfilterx"
    su debian-transmission -c "gunzip -f btlevel1.gz nexus23.gz"
#    sleep 25s
#    /etc/init.d/transmission-daemon start
fi
