#!/bin/sh

if [ `hostname` = "moe" ]; then
    su torrent
    cd ~/.config/transmission/blocklists
    wget -O btlevel1 http://list.iblocklist.com/?list=bt_level1
    wget -O nexus23 http://list.iblocklist.com/?list=nxs23_ipfilterx
fi
