#!/bin/bash

DIR="/storage/abstract/videos"

if [ "$1" = "autoconf" ]; then
    echo yes
    exit 0
fi
if [ "$1" = "config" ]; then
    echo "graph_title Videos per genre
graph_args -l 0
graph_category disk
graph_info This graph shows the amount of videos stored per genre"

    cd $DIR
    for dir in *; do 
	if [ -d $dir ]; then
	    echo "$dir.label `basename $dir`"
	    echo "$dir.draw AREASTACK"
	fi
    done
    exit 0
fi


cd $DIR
for dir in *; do 
    if [ -d $dir ]; then
	echo "$dir.value `du -s $dir | tr -d [:alpha:][:blank:]`000"
    fi
done
