#!/usr/bin/perl
#
# Pendant de procmail, envoie des archives dans mail-vers-archives que
# cron.hourly/mail-archives traitera.
#
# $Id: cgn_mailarchives_fromemacs,v 1.4 2003-12-17 08:17:29 cgn-ulysse Exp $

use Sys::Hostname;
use POSIX qw(strftime);

do "/etc/hosts.nib.pl" or exit;
exit unless $server;
exit if hostname() eq $server;
exit unless -e "/home/transit/.hephaistos";

my @users = ("moa", "egh");
my $log = "/var/log/mail.archiving";

open(LOG, ">> $log");
print LOG "--> ".strftime("%Y-%m-%d %H:%M:%S", localtime)."\n";

# Emacs met mes archives dans un fichier dans .Mail/archive/mail/YYYY-MM
# (pas de *.mbox)

my $user = "moa";
my $thismonth = strftime("%Y-%m", localtime);
my $gnusarchivedir = "/home/$user/.Mail/archive/mail";
# NFS3 ne permet pas d'écrire en root direct là, avec la gestion des droits
my $tmpversarchivedir = "/home/$user/.tmp-mail-vers-archives";
my $versarchivedir = "$user\@he:/home/$user/mail-vers-archives";  
my $done = 0;

`mkdir $tmpversarchivedir`;
opendir(DIR, $gnusarchivedir);

while (defined(my $mbox = readdir(DIR))) {
    next if $mbox =~ m/(.*)\~$/;
    next if $mbox =~ m/(.*)\.nov$/;
    next if $mbox =~ m/(.*)\.mrk$/;
    next if $mbox =~ m/^\.$/;
    next if $mbox =~ m/^\.\.$/;
    next if $mbox =~ m/$thismonth/;
    open(IN, "< $gnusarchivedir/$mbox");
    open(OUT, ">> $tmpversarchivedir/$mbox.mbox");
    while (<IN>) {
	print OUT $_;
    }
    close(FILE);
    unlink($gnusarchivedir."/".$mbox);
    print LOG "A traité $mbox pour $user\n";
    $done = 1;
}

`su $user -c "scp $tmpversarchivedir/* $versarchivedir/"` if $done;
print LOG "A effectué mv $tmpversarchivedir/* $versarchivedir/ pour $user\n" if $done;
`rm -rf $tmpversarchivedir`;
closedir(DIR);

  
print LOG strftime("%Y-%m-%d %H:%M:%S", localtime)." <--\n";
# End
