#!/usr/bin/perl

use File::Basename;

open(LIST, "find /etc/cron.hourly /etc/cron.daily /etc/cron.weekly /etc/cron.monthly ! -name \"*~\" ! -name \"*.dpkg-old\" -mindepth 1 |");
while (<LIST>) {
    chomp($_);
    my $basename = basename($_);
    # assume that names are uniques ; currently enough for now
    `ln -s $_ /usr/local/bin/cron.$basename` unless -e "/usr/local/bin/cron.$basename";
}
close(LIST);


