#!/usr/bin/perl
#
# $Id: cgnserv_spamzor_discover,v 1.1 2004-12-05 22:22:55 moa Exp $

use Sys::Hostname;

do "/etc/hosts.nib.pl" or exit;
exit unless $server;
exit if hostname() ne $server;

system("/usr/bin/razor-admin",
       "-home=/etc/spamassassin/.razor",
       "-discover");

system("/usr/bin/pyzor",
       "--homedir",
       "/etc/spamassassin/.pyzor",
       "discover");

# End
