#!/bin/sh
# $Id: cgnserv_aptarchive_removeoldpackages,v 1.2 2005-10-15 12:42:45 moa Exp $

. /etc/hosts.nib.sh
if [ ! $SERVER ]; then exit ; fi
if [ `hostname` != $SERVER ]; then exit ; fi 

LOG=/var/log/cgn_apt-ftparchive.log
echo "---- apt-ftparchive (removing older packages) `date` ---->>" >> $LOG
# Maintain the local deb archives
export basedir=/stock/debian
export dirdl=testing
export newer=$basedir/$dirdl/newer
# every week, remove remove downloaded packages older than a week 
# this is managed in /etc/cron.weekly
# everything else is in /etc/cron.d/apt-ftparchive
#        we generate a file to be able to use -newer
#        all files added after are newer
#        a week later, the script rerun
#        we remove files that are not newer
#        that means files older than the previous
#        time we run that script
if [ ! -e $newer ]; then 
    OLD=""
else
    touch $basedir/$dirdl/pouet.deb
    OLD=`find $basedir/$dirdl/*.deb ! -newer $newer`
    rm $newer $basedir/$dirdl/pouet.deb
fi
touch $newer

for old in $OLD; do
    if [ $old != "" ] ; then  rm -fv $old >> $LOG ; fi
done	 
echo "<<---- apt-ftparchive (removing older packages) `date` ---" >> $LOG

